# This is an example/template project script in fpga/projects/a3pe_proto_kit/.
# Files in this directory capture vendor-specific project configuration for
# the A3PE (ProASIC3E) prototype kit.
# Replace this script with the actual project files generated by your FPGA
# toolchain, or adapt it to recreate the project from source.

# Example: add HDL, constraint, and simulation files from ../src, ../constr, ../sim.
# TODO: add vendor tool commands here.

